#!/usr/bin/ash

run_earlyhook()	{
	msg ":: Activating authentication..."
}

login_shell() {
	export PS1='[rootfs \W]\$ '
	{
		login
	} 0</dev/console 1>/dev/console 2>/dev/console
}

# Override function
launch_interactive_shell() {
	msg ":: Starting shell"
	login_shell
}
